services:
  web:
    build: ../web
    image: llm-chatbot
    ports:
      - "8051:8050"
    models:
      - llm
    extra_hosts:
      - "model-runner.docker.internal:host-gateway"
    environment:
    - LLM_BASE_URL=${LLM_BASE_URL}

models:
  llm:
    model: ai/smollm2